name: Cron Monitor Golar

on:
  schedule:
    # Se ejecuta todos los viernes a las 20:00 UTC (21:00h en España)
    - cron: '0 20 * * 5'
  workflow_dispatch: # Permite que tú lo lances manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerias necesarias
        run: |
          pip install yfinance pandas matplotlib requests

      - name: Ejecutar Monitor Golar
        run: python monitor_golar.py
